apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shoutan-login-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: shoutan-login
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: registry-vpc.cn-qingdao.aliyuncs.com/shoutan/shoutan-login:latest
        name: shoutan-login
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: shoutan-login
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1
      imagePullSecrets:
      - name: aliyun-qingdao-registry-secret